### ISSUE TITLE
TileGrid Issues

### ISSUE THREAD

**Issue by bodily11** [arcadefx/material-ui#163]
I'm using your material-ui and it's awesome. Thanks for the great resource. I've been having a few troubles, and I didn't know where else to contact you about this, so I'm adding it as an issue. 

1. I can't find the right attribute to change the font-size of labels within a TileGrid. I tried any I could find on Corona documentation, both in the TileGrid options and the list options within the TileGrid options but nothing worked.
2. I can't find the right attribute to add the TileGrid to the parent object sceneGroup to remove it when I go to another scene (using composer). I tried adding each list item individually, and also tried adding a parent = sceneGroup field in the TileGrid options. Neither one worked.

Thank you.

**Comment by arcadefx** [comment]
@bodily11
1. I will get this addressed.  I will make it have a default font size and the ability to change the font size.
2. I will look into it and fix this too.

**Comment by arcadefx** [comment]
@bodily11 Fixed. See changes below..

## [0.1.61] - 2017-01-20
### Added
- 'iconImage' parameter to newTileGrid() list options. Allows a tile to use an image (jpg/png) instead of icon font text.
- 'fontIsScaled' parameter to newTileGrid(). Defaults to true.  If true scale the font to fit the width of the tile. If false let the user define the font to any size.
- 'fontSize' parameter to newTileGrid(). Sets the overall font size for icon and text.
- 'parent' parameter to newTileGrid().  If used it will place the newTileGrid widget into the group/parent.

**Comment by bodily11** [comment]
Font size changes and adding to parent/group work great. Thanks for the quick fix!
